### ISSUE TITLE
Files > 1.5 MB not uploading

### ISSUE THREAD

**Issue by vishalinfyom** [short-pixel-optimizer/shortpixel-php#21] opened 2021-04-07 06:47 UTC
Hello,

I'm using following code to store my files, with smaller size of files (up to 1 MB) its working fine, when I'm uploading files > 2 MB, its not working.

```
 \ShortPixel\setKey(config('app.short_pixel_key'));
  \ShortPixel\ShortPixel::setOptions(["wait" => "300"]);
 $diskPath = Storage::disk($disk)->getAdapter()->getPathPrefix();
 $data = \ShortPixel\fromBuffer($fileName, $contents)->toFiles($path);
```

Thanks

**Comment by short-pixel-optimizer** [comment] 2021-04-12 04:35
Hi @vishalinfyom thank you for spotting this. The issue is fixed by https://github.com/short-pixel-optimizer/shortpixel-php/commit/0249070d135d7928f0631b8a0f33fed4df5bf50d

**Closed as completed by short-pixel-optimizer** 2021-04-12 04:35 UTC
