### ISSUE TITLE
CLI Tool PHP Errors - Undefined variable: result

### ISSUE THREAD

**Issue by praggmatica** [short-pixel-optimizer/shortpixel-php#5] opened 2017-10-01 00:06 UTC
I have a purchased monthly plan with your product. I have used the WP plugin successfully, but for some non-WP sites, would like to use the CLI tool. Followed [the instructions here](https://shortpixel.com/cli-docs) to use.

What I did: 
Ran `sudo php shortpixel-php-master/lib/cmdShortpixelOptimize.php --apiKey=XXX --folder=images`
The first run completed successfully, with a message "Images still pending, please relaunch the script to continue."

Ran it a second time. Received the following PHP errors, and the script exited out.

```
PHP Notice:  Undefined variable: result in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 132
PHP Notice:  Trying to get property of non-object in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 132
PHP Notice:  Undefined variable: result in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 135
PHP Notice:  Trying to get property of non-object in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 135
PHP Notice:  Undefined variable: result in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 138
PHP Notice:  Trying to get property of non-object in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 138
PHP Notice:  Undefined variable: result in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 141
PHP Notice:  Trying to get property of non-object in shortpixel-php-master/lib/cmdShortpixelOptimize.php on line 141
```

What I expected:
The second run to continue optimizing the remainder of the images pending.

Can you look into? Thanks.

**Comment by simondud** [comment] 2017-10-01 13:29
Hi Chris,

Thanks for letting me know about this and sorry for the problem. Please allow me until tomorrow to check it and I'll let you know.

Best regards,
Simon.

**Comment by simondud** [comment] 2017-10-03 11:08
Hi Chris,

Did several tests on my environment but could not reproduce it. I committed a new version which could shed more light on the error. If not, could you please provide me the folder you're trying to optimize? We could discuss this further on our support platform (https://shortpixel.com/contact) and then post back here the conclusions, if you like.

Cheers,
Simon.

**Comment by simondud** [comment] 2017-10-26 16:37
Hi Chris, 

The new 1.0.1 version has several fixes, could you please try this one?

Cheers,
Simon.

**Closed as completed by simondud** 2017-10-26 16:37 UTC

**Comment by praggmatica** [comment] 2017-11-01 01:12
Hi Simon,

This new version works without a problem on the same directory of images. Thank you!

**Comment by simondud** [comment] 2017-11-02 18:09
Great! Thank you too for your patience.
